# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

professions = Profession.create!([{name: "Abogados"},
																  {name: "Administración"},
																	{name: "Agrónomos"},
																	{name: "Arquitectos"},
																	{name: "Arte"},
																	{name: "Asesoría"},
																	{name: "Auditoría"},
																	{name: "Banca"},
																	{name: "Bodega"},
																	{name: "Cajero"},
																	{name: "Call Center Bilingüe"},
																	{name: "Call Center Cobros"},
																	{name: "Call Center no Bilingüe"},
																	{name: "Catedráticos"},
																	{name: "Comercial"},
																	{name: "Compras"},
																	{name: "Comunicación"},
																	{name: "Construcción"},
																	{name: "Contabilidad"},
																	{name: "Control de calidad"},
																	{name: "Costura y Confección"},
																	{name: "Digitadores"},
																	{name: "Diseño"},
																	{name: "Economistas"},
																	{name: "Edecanes"},
																	{name: "Electrificación"},
																	{name: "Enfermeras"},
																	{name: "Esteticismo"},
																	{name: "Finanzas"},
																	{name: "Fines de semana"},
																	{name: "Fotografía"},
																	{name: "General"},
																	{name: "Gerencias"},
																	{name: "Hotelería y Restaurantes"},
																	{name: "Importaciones-Exportaciones"},
																	{name: "Informática/Internet"},
																	{name: "Ingenieros"},
																	{name: "Jefaturas"},
																	{name: "Jurídico"},
																	{name: "Logística"},
																	{name: "Médicos"},
																	{name: "Música"},
																	{name: "Maestros"},
																  {name: "Mantenimiento"},
																	{name: "Mecánicos"},
																	{name: "Medio tiempo"},
																	{name: "Mensajería"},
																	{name: "Mercadeo"},
																	{name: "Nutrición"},
																	{name: "Operativa"},
																	{name: "Pilotos"},
																	{name: "Practicantes"},
																	{name: "Promotores"},
																	{name: "Psicólogos"},
																	{name: "Publicidad"},
																	{name: "Química Farmacéutica"},
																	{name: "Receptor/Pagador"},
																	{name: "Recursos Humanos"},
																	{name: "Relaciones Públicas"},
																	{name: "Salud"},
																	{name: "Secretarias"},
																	{name: "Seguridad"},
																	{name: "Seguros"},
																	{name: "Servicio al cliente"},
																	{name: "Sonido"},
																	{name: "Supermercados"},
																	{name: "Supervisores"},
																	{name: "Técnicos"},
																	{name: "Telecomunicaciones"},
																	{name: "Temporal"},
																	{name: "Trabajo Social"},
																	{name: "Traductores Jurado"},
																	{name: "Tramitador Aduanal"},
																	{name: "Vacacionistas"},
																	{name: "Ventas"},
																	{name: "Veterinario"},
																	{name: "Visitador Médico"},
																	{name: "Zootecnista"},
																	{name: "Otro"}
																 ]
																)